# Generated by Django 2.1.5 on 2023-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('CommentID', models.AutoField(max_length=127, primary_key=True, serialize=False, verbose_name='c_id')),
                ('AuthorID', models.CharField(max_length=127, null=True, verbose_name='a_id')),
                ('Comment', models.TextField(max_length=512, null=True, verbose_name='comment')),
                ('ThreadID', models.IntegerField(max_length=20, null=True, verbose_name='id')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='forum',
            fields=[
                ('ForumID', models.IntegerField(max_length=127, null=True, verbose_name='F_id')),
                ('CourID', models.IntegerField(max_length=512, null=True, verbose_name='C_id')),
                ('ThreadID', models.AutoField(max_length=127, primary_key=True, serialize=False, verbose_name='t_id')),
            ],
            options={
                'db_table': 'forum',
            },
        ),
        migrations.CreateModel(
            name='thread',
            fields=[
                ('ThreadID', models.AutoField(max_length=127, primary_key=True, serialize=False, verbose_name='t_id')),
                ('AuthorID', models.IntegerField(max_length=127, null=True, verbose_name='A_id')),
                ('Thr_mes', models.TextField(max_length=512, null=True, verbose_name='t_m')),
                ('title', models.TextField(max_length=512, null=True, verbose_name='title')),
            ],
            options={
                'db_table': 'thread',
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(max_length=127, null=True, verbose_name='t_id')),
                ('UserName', models.CharField(max_length=127, null=True, verbose_name='u_id')),
                ('type', models.TextField(max_length=512, null=True, verbose_name='type')),
                ('FirstName', models.CharField(max_length=127, null=True, verbose_name='f_name')),
                ('LastName', models.CharField(max_length=127, null=True, verbose_name='L_name')),
                ('intro', models.TextField(max_length=512, null=True, verbose_name='intro')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
