# Generated by Django 2.1.5 on 2023-03-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(blank=True, to='simplify_main_app.Course'),
        ),
    ]
