# Generated by Django 2.1.5 on 2023-03-20 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='course',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='simplify_main_app.Course'),
        ),
    ]
