# Generated by Django 2.1.5 on 2023-03-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
