# Generated by Django 2.2.5 on 2023-03-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0002_auto_20230306_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='tutor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STD', 'Student'), ('TUT', 'Tutor')], max_length=3),
        ),
    ]
