# Generated by Django 2.1.5 on 2023-03-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0002_auto_20230320_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course_id',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='simplify_main_app.Course'),
        ),
    ]
