# Generated by Django 2.1.5 on 2023-03-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0002_auto_20230320_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, to='simplify_main_app.Course'),
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, to='simplify_main_app.Course'),
        ),
    ]
