# Generated by Django 2.1.5 on 2023-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0002_auto_20230306_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('course_name', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=1024)),
                ('material', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='tutor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STD', 'Student'), ('TUT', 'Tutor')], max_length=3),
        ),
    ]
