# Generated by Django 2.1.5 on 2023-03-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0003_auto_20230316_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
    ]
