# Generated by Django 2.1.5 on 2023-03-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0004_auto_20230316_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
    ]
