# Generated by Django 2.1.5 on 2023-03-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0005_remove_course_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='tutor_id',
        ),
    ]
