# Generated by Django 2.1.5 on 2023-03-19 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0008_auto_20230319_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'ordering': ['course_id']},
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
