# Generated by Django 2.1.5 on 2023-03-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_main_app', '0009_auto_20230319_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={},
        ),
    ]
